//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public CLASS()
        {
            this.STUDENTs = new HashSet<STUDENT>();
        }
    
        public int ID { get; set; }
        public string CLASSNAME { get; set; }
    
        public virtual ICollection<STUDENT> STUDENTs { get; set; }
    }
}
